name: Codari_Core
version: 0.1.5
main: com.codari.apicore.CodariCore
depend: [ProtocolLib]

commands:
  ca:
    description: get all the comands for Codari Arena
    usage: Simply type in "/ca"